version: '3.1'
services:

  redis:
    image: 'bitnami/redis:7.0.5'
    networks:
      - hmpps_int
    container_name: redis_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  wiremock_auth:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: wiremock_auth_int
    restart: always
    ports:
      - "9091:8080"

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: wiremock_int
    restart: always
    volumes:
      - ./mappings:/home/wiremock/mappings
    ports:
      - "9092:8080"

  gotenberg:
    image: gotenberg/gotenberg:7.7.0
    networks:
      - hmpps_int
    container_name: gotenberg_int
    ports:
      - "3001:3001"
    command:
      - "gotenberg"
      - "--api-port=3001"
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--pdfengines-engines=pdftk"
      - "--uno-listener-restart-threshold=0" #disables uno listener
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3001/health' ]

  postgres:
    image: postgres:13.8
    networks:
      - hmpps_int
    container_name: postgres_int
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pre-sentence-service
      - POSTGRES_USER=pre-sentence-service
      - POSTGRES_DB=pre-sentence-service

  localstack:
    image: localstack/localstack:1.2.0
    networks:
      - hmpps_int
    container_name: localstack_int
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
    environment:
      - SERVICES=sns
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI-8088}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL-localstack}
    volumes:
      - './.localstack:/tmp/localstack'
      - $PWD/localstack:/docker-entrypoint-initaws.d

  wproofreader:
    image: quay.io/hmpps/pre-sentence-service-wproofreader:latest
    networks:
      - hmpps_int
    container_name: wproofreader_int
    ports:
      - "8081:8081"
    command:
      - ${WP_LICENSE_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/wscservice/api?cmd=ver" ]

networks:
  hmpps_int:
