version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: pre-sentence-service-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13.3
    networks:
      - hmpps
    container_name: pre-sentence-service-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pre-sentence-service
      - POSTGRES_USER=pre-sentence-service
      - POSTGRES_DB=pre-sentence-service

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: pre-sentence-service-hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  gotenberg:
    image: thecodingmachine/gotenberg:6.4.4
    networks:
      - hmpps
    container_name: pre-sentence-service-gotenberg
    ports:
      - "3001:3000"
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/ping' ]

  localstack:
    image: localstack/localstack:0.13.2
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
    environment:
      - SERVICES=${SERVICES-sqs}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI-8088}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL-localstack}
    volumes:
      - './.localstack:/tmp/localstack'
      - $PWD/localstack:/docker-entrypoint-initaws.d

  app:
    build: .
    networks:
      - hmpps
    depends_on: [ redis, postgres, gotenberg, localstack ]
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      # These will need to match new creds in the seed auth service auth
      - API_CLIENT_ID=client-id
      - API_CLIENT_SECRET=client-secret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret

networks:
  hmpps:
