version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps_int
    container_name: pre-sentence-service-redis_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    container_name: pre-sentence-service-wiremock_int
    restart: always
    ports:
      - "9091:8080"

  gotenberg:
    image: thecodingmachine/gotenberg:6.4.4
    networks:
      - hmpps_int
    container_name: gotenberg
    ports:
      - "3001:3000"
    restart: always
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/ping' ]

  postgres:
    image: postgres
    networks:
      - hmpps_int
    container_name: pre-sentence-service-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pre-sentence-service
      - POSTGRES_USER=pre-sentence-service
      - POSTGRES_DB=pre-sentence-service

networks:
  hmpps_int:
