---
generic-service:
  nameOverride: pre-sentence-service

  replicaCount: 4

  image:
    repository: quay.io/hmpps/pre-sentence-service
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: pre-sentence-service-cert
    path: /

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    DATABASE_SCHEMA: "presentenceservice"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    pre-sentence-service:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    pac-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    pre-sentence-service-rds-instance-output:
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
      DB_SERVER: "rds_instance_address"
      DB_SSL_ENABLED: "true"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

#gotenberg:
#  nameOverride: gotenberg
#  replicaCount: 2
#
#  image:
#    repository: thecodingmachine/gotenberg
#    tag: 6.4.4
#    port: 3000
#
#  ingress:
#    enabled: false
#
#  livenessProbe:
#    httpGet:
#      path: /ping
#    periodSeconds: 30
#    initialDelaySeconds: 60
#    timeoutSeconds: 20
#    failureThreshold: 10
#
#  readinessProbe:
#    httpGet:
#      path: /ping
#    periodSeconds: 20
#    initialDelaySeconds: 60
#    timeoutSeconds: 30
#    failureThreshold: 15
#
#  podSecurityContext:
#    fsGroup: 1001
#
#  securityContext:
#    runAsUser: 1001
#    runAsNonRoot: true

#generic-prometheus-alerts:
#  targetApplication: pre-sentence-service
#  alertSeverity: prepare-a-case
