---
# Per environment values which override defaults in pre-sentence-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: pre-sentence-service-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-preprod-cert-secret

  env:
    INGRESS_URL: "https://pre-sentence-service-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    GOTENBERG_API_URL: "http://pre-sentence-service-gotenberg"
    PRE_SENTENCE_URL: "http://pre-sentence-service"

  allowlist:
    delius-pre-prod-1: "52.56.240.62/32"
    delius-pre-prod-2: "18.130.110.168/32"
    delius-pre-prod-3: "35.178.44.184/32"

gotenberg:
  replicaCount: 1

  env:
    GOOGLE_CHROME_IGNORE_CERTIFICATE_ERRORS: 1
    DISABLE_UNOCONV: 1
    DEFAULT_WAIT_TIMEOUT: 30
