---
# Per environment values which override defaults in pre-sentence-service/values.yaml

generic-service:

  ingress:
    host: pre-sentence-service.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  env:
    INGRESS_URL: "https://pre-sentence-service.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    COMMUNITY_API_URL: "https://community-api.probation.service.justice.gov.uk"
    PRE_SENTENCE_TO_DELIUS_API_URL: "https://pre-sentence-reports-to-delius.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    GOTENBERG_API_URL: "http://pre-sentence-service-gotenberg"
    PRE_SENTENCE_URL: "http://pre-sentence-service"
    WPROOFREADER_PROTOCOL: 'https'
    WPROOFREADER_HOST: 'pre-sentence-service-wproofreader.hmpps.service.justice.gov.uk'
    WPROOFREADER_PORT: null

  allowlist:
    groups:
      - delius-prod

wproofreader:

  ingress:
    host: pre-sentence-service-wproofreader.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  allowlist:
    groups:
      - delius-prod

