---
# Per environment values which override defaults in pre-sentence-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: pre-sentence-service-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-preprod-cert-secret

  env:
    INGRESS_URL: "https://pre-sentence-service-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    COMMUNITY_API_URL: "https://community-api.pre-prod.delius.probation.hmpps.dsd.io"
    PRE_SENTENCE_TO_DELIUS_API_URL: "https://pre-sentence-reports-to-delius-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    GOTENBERG_API_URL: "http://pre-sentence-service-gotenberg"
    PRE_SENTENCE_URL: "http://pre-sentence-service"
    WPROOFREADER_PROTOCOL: 'https'
    WPROOFREADER_HOST: 'pre-sentence-service-wproofreader-preprod.hmpps.service.justice.gov.uk'
    WPROOFREADER_PORT: null

  allowlist:
    groups:
      - delius-pre-prod

gotenberg:
  replicaCount: 1

wproofreader:

  ingress:
    host: pre-sentence-service-wproofreader-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-preprod-cert-secret

    allowlist:
      groups:
        - delius-pre-prod
