---
# Per environment values which override defaults in pre-sentence-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: pre-sentence-service-dev.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-dev-cert-secret

  env:
    INGRESS_URL: "https://pre-sentence-service-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    COMMUNITY_API_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    PRE_SENTENCE_TO_DELIUS_API_URL: "https://pre-sentence-reports-to-delius.test.probation.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    GOTENBERG_API_URL: "http://pre-sentence-service-gotenberg"
    PRE_SENTENCE_URL: "http://pre-sentence-service"
    WPROOFREADER_PROTOCOL: 'https'
    WPROOFREADER_HOST: 'pre-sentence-service-wproofreader-dev.hmpps.service.justice.gov.uk'
    WPROOFREADER_PORT: null

  allowlist: null

gotenberg:
  replicaCount: 1

wproofreader:

  ingress:
    host: pre-sentence-service-wproofreader-dev.hmpps.service.justice.gov.uk
