---
# Per environment values which override defaults in pre-sentence-service/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: pre-sentence-service.hmpps.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  env:
    INGRESS_URL: "https://pre-sentence-service.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    GOTENBERG_API_URL: "http://pre-sentence-service-gotenberg"
    PRE_SENTENCE_URL: "http://pre-sentence-service"

  allowlist:
    delius-prod-1: "52.56.115.146/32"
    delius-prod-2: "35.178.104.253/32"
    delius-prod-3: "35.177.47.45/32"

gotenberg:
  replicaCount: 1

  env:
    GOOGLE_CHROME_IGNORE_CERTIFICATE_ERRORS: 1
    DISABLE_UNOCONV: 1
    DEFAULT_WAIT_TIMEOUT: 30
